// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqcbxwvkjzlrrkmjszh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncWNieHd2a2p6bHJya21qc3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzY4ODEsImV4cCI6MjA2MzIxMjg4MX0.8MQIhVYNOQxPI6BGVnGM2FSij9Sve_LkhXu1sqer5WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);